### ISSUE TITLE
`gpm_track.py` generates error when running scripts on observation file that contains only one ObsID

### ISSUE THREAD

**Issue by robotopia** [robotopia/MWA-Galactic-Plane-Monitoring#25]
Example:
```
> echo $GPMGITVERSION 
v0.6-28-g6665398

> obs_giantsquid.sh -o Epoch0810_calibrations.txt 
Traceback (most recent call last):
  File "/software/projects/pawsey0272/smcsweeney/MWA-Galactic-Plane-Monitoring/gpm_track.py", line 484, in observation_epochs
    obs_ids = tuple([int(o) for o in np.loadtxt(obs_file)])
TypeError: iteration over a 0-d array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/projects/pawsey0272/smcsweeney/MWA-Galactic-Plane-Monitoring/gpm_track.py", line 1034, in <module>
    observation_epochs(args.obs_file)
  File "/software/projects/pawsey0272/smcsweeney/MWA-Galactic-Plane-Monitoring/gpm_track.py", line 486, in observation_epochs
    raise ValueError(f"Could not load obsids from file '{obs_file}'")
ValueError: Could not load obsids from file 'Epoch0810_calibrations.txt'
Obs 1405427216 is not in your ASVO job list. Adding it to the preprocessing list
===================================
Preprocessing list:  1405427216
16:01:11 [WARN] Using 'acacia' for ASVO delivery
16:01:12 [INFO] Submitted 1405427216 as ASVO job ID 783256
16:01:12 [INFO] Submitted 1 obsids for conversion.

Preprocessing jobs sent to ASVO
No download jobs sent
```
where `Epoch0810_calibrations.txt` contains only:
```
1405427216
```

**Comment by robotopia** [comment]
Fixed in 941297f (and in the several commits before that)
